### ISSUE TITLE
unable to download SpliceSeq

### ISSUE THREAD

**Issue by OmniaUsama92** [MD-Anderson-Bioinformatics/SpliceSeq#10]
I am unable to download or launch spliceseq from MD anderson page, is it still available?

**Comment by ChrisWakefield** [comment]
Sorry for the delayed response.
I notice Chrome's behavior has changed when it encounters a link that is not HTTPS when accessed from a page that is HTTPS.  If I click on the "SpliceSeq.zip" link, it just ignores me.  However, if I use control-click (right click), I can select the "Save Link as ..." option from the popup menu.  Alternatively, if I just paste the URL in another window, it works fine http://projects.insilico.us.com/SpliceSeq_2.3/SpliceSeq.zip.  (THIS LINK NO LONGER WORKS as reported in April 2024.  I hope to provide a new link.)

Firefox has different behavior, and it pops up a Save As dialog just from clicking the link.  There may be other variations with other browsers and platforms.

I suspect that launching spliceseq as a Java Web Start application may have similar problems.  I'm not currently using Java Web Start anymore, and will need to do more work to test that.

Does this help?

**Comment by SvetlanaKhorkova** [comment]
Thank you for the answer!
It helped to solve the problem
