### ISSUE TITLE
Transferring Study Data to another computer

### ISSUE THREAD

**Issue by mitchellcheung8** [MD-Anderson-Bioinformatics/SpliceSeq#11]
Thank you for designing such a wonderful program! I was able to get better descriptive and visual analysis of alternative splicing than the default DEXSeq analysis done by Genewiz.

I performed my group comparison analysis with SpliceSeq on my "beefy" Win10 home desktop in a relatively short time using a local MySQL installed on the same computer.  I wanted to have a copy of the program/analysis on my work Win10 laptop, so I copied the SpliceSeq folder over.

However, I was unable to open up the Study Data results on the laptop.
What I tried:
I clicked on "Load Study Data" and was able to see the name of the study that was previously done. I clicked on "Run" and the "stat" log showed that all the steps were "Previously Completed" with the last line saying the analysis was "Successfully Processed".  However, clicking "Sample view", or "Group Comparison View" did not show the study on the list.

The "Graphview" loaded with no issues (The connected MySQL database is running on a NAS home server, which is different from the original WIn10 local MySQL server).

Is there a way to transfer the Study data results?  Are there other files on my Win10 Desktop that should be transferred over besides the SpliceSeq folder? I don't want to redo the analysis on the Laptop as it is much less powerful and would probably take "weeks" to process.  I can remote log in to my home Desktop to look at the analysis, but I also want to share the program and results with my colleagues on their own PC so they can review the data themselves.

Thank you for your help.

UPDATE...

I think I might have figured out the issue.  As I mentioned, the original data processing was done on my desktop using a locally installed MySQL database server also running on the desktop.

When I decided to try to transfer over the SpliceSeq folder to my work laptop, I set up a new MySQL server on a different home system (QNAP-brand NAS running 24 hours) to allow for remote TCP access. In the process of troubleshooting, when I configure the home Desktop SpliceSeq program to access the new MySQL database, I ran into the same issue of not seeing the previously processed Study. I don't have any technical knowledge of the MySQL server system obviously, but it appears that the MySQL database on my Desktop has modifications/data that will need to be transferred over to the new MySQL database as well?

Is this correct?  I prefer not to keep my home Dekstop running all the time as a remote MySQL server, so I will try to transfer the SpliceGraph database to the NAS  and let you know how it goes.

**Comment by ChrisWakefield** [comment]
Thanks for the compliments, even though I can't personally take credit for it.
Yes, you are correct.  The results are in the MySQL database.
As you can see at https://bioinformatics.mdanderson.org/public-software/spliceseq/installation/#configuring , you must tell SpliceSeq Viewer how to access the MySQL database, such as where the database resides and the user and password to use.
Moving this database from one server to another is specific to MySQL.  I suggest the mysqldump tool (https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html) should be the most robust way to export your entire SpliceSeq database as a text file, that can then be moved to another computer and loaded via the mysql tool(s).  There are other ways to accomplish the same thing, but this may be easiest.

**Comment by ChrisWakefield** [comment]
The database name you want is likely either SpliceGraph or splicegraph.  The MySQL tools on your computer can show you what databases are available ("Show databases" on the mysql command line).

**Comment by mitchellcheung8** [comment]
Thank you Chris.  Everything is up and running now after transferring the MySQL database.

On a different note, I notice that you mention to another user in Github to make sure to download the newest version of 2.3 from  http://projects.insilico.us.com/SpliceSeq_2.3/SpliceSeq.zip
The version in the zip file link is actually version 2.1, according to the 'About SpliceSeq' menu option in the Help menu of the program.

**Comment by ChrisWakefield** [comment]
Closing as resolved.
