### ISSUE TITLE
Still unable to connect to splicegraph

### ISSUE THREAD

**Issue by tujizju** [MD-Anderson-Bioinformatics/SpliceSeq#3]
Hi!
When I run SpliceSeq as mentioned on the Spliceseq website, a error(database connect error: unable to connect to splicegraph20) came out. 
As you've already replied in another issue, the sample SpliceSeq database wasn't setup, and would be restoring. I wonder if the setup of the database completes now? 

Thanks, 
Hang

**Comment by mryaninsilico** [comment]
Hang,

 

Are you trying to analyze your own RNASeq data with SpliceSeq?  If so, you need to install a local empty version of the database by following the instructions here: https://bioinformatics.mdanderson.org/public-software/spliceseq/installation/.

 

If you are just interested in TCGA data, you can use the download function here to get data that you want: https://bioinformatics.mdanderson.org/TCGASpliceSeq/PSIdownload.jsp

 

Mike

**Comment by ChrisWakefield** [comment]
Apparently solved since 2019.
