### ISSUE TITLE
Splice Seq DB connection error

### ISSUE THREAD

**Issue by k1muk** [MD-Anderson-Bioinformatics/SpliceSeq#4]
Hello  @mryaninsilico 

I am trying to launch a local SpliceSeq.jar file. When I double click it, it throws a connection error while trying to connect to SpliceGraph20 @"jdbc:ratway://projects.insilico.us.com/Ratway/RW".

I would like to work with your sample DB, that has processed data from TCGA. I don't have my own data to create a local DB. 
I tried using your online version- but it doesn't give me options for comparative analysis or p-values.....

Any work around or pointers on how I can go about resolving this issue, will be much appreciated.

And thank you for this tool!

Thanks,
Kavitha

**Comment by mryaninsilico** [comment]
Kavitha,

 

Thanks for your interest in SpliceSeq.  The easiest way to get TCGA splicing in formation is to use the TCGA SpliceSeq site here:  https://bioinformatics.mdanderson.org/TCGASpliceSeq/ or on our beta site that has some new features like clinical data: http://projects.insilico.us.com/TCGASpliceSeq/.  You can interactively look at specific genes or go to the download page and get PSI values for each sample / splice event.

 

Try that out and let me know if you have specific follow up questions.

 

Thanks,

 

Mike Ryan, PhD

In Silico Solutions

**Comment by k1muk** [comment]
Hello,

Thanks for getting back to me. But, TCGAspliceseq doesn't give me an option
to download PSI values for non-tumor samples. Because, when I input sample
ids as, say "TCGA-A6-5655", I don't provide the sample type information (01
or 11).
Am I missing something here?

My end goal was to identify dPSI for a select set of samples with a TCGA
cohort...

*Thanks,*
*Kavitha*

**Comment by mryaninsilico** [comment]
Kavitha,

 

When you download PSI values, you can leave the sample id specification empty and it will download all samples for the tumor type selected.  The sample IDs that end with ‘_Norm’ are the matched normal samples.  For samples that have adjacent normal sequencing, you will get two columns in the download PSI matrix, one like TCGA-A6-5655 for the tumor sample and the other like TCGA-A6-5655_Norm.

 

Mike

**Comment by k1muk** [comment]
Hello,
So sorry, my bad, I never noticed the "_norm" column names. I had downloaded the entire file much earlier.
I guess, I should have just parsed it, rather than giving it a visual inspection :)
Thanks again!
-Kavitha
