### ISSUE TITLE
The documentation's link is unaccessible.

### ISSUE THREAD

**Issue by Syu1106** [MD-Anderson-Bioinformatics/SpliceSeq#7]
Hi,
when I visit the documentation's web site,It  prompts “503 Service Unavailable”.Could you provide another valid link or send me a profile? my email address is sy1106@mail.ustc.edu.cn
Kind Regards,
sy

**Comment by ChrisWakefield** [comment]
@Syu1106 That website was temporarily down.  It is working just now at https://bioinformatics.mdanderson.org/public-software/spliceseq/
